<?php
    include_once(DIR_FS_CLASSES."users.class.php");
    include_once(DIR_FS_CLASSES."admin.class.php");
    include_once(DIR_FS_CLASSES."manage_broker.class.php");
    include_once(DIR_FS_CLASSES."manage_account.class.php");
    include_once(DIR_FS_CLASSES."manage_product.class.php");
    include_once(DIR_FS_CLASSES."manage_payroll.class.php");
    include_once(DIR_FS_CLASSES."client_suitebility.class.php");
    include_once(DIR_FS_CLASSES."client_maintenance.class.php");
    include_once(DIR_FS_CLASSES."product_maintenance.class.php");
    include_once(DIR_FS_CLASSES."system_configuration.class.php");
    include_once(DIR_FS_CLASSES."date_interfaces.class.php");
    include_once(DIR_FS_CLASSES."manage_company.class.php");
    include_once(DIR_FS_CLASSES."manage_sponsor.class.php");
    include_once(DIR_FS_CLASSES."branch_maintenance.class.php");
    include_once(DIR_FS_CLASSES."batches.class.php");
    include_once(DIR_FS_CLASSES."import.class.php");
    include_once(DIR_FS_CLASSES."transaction.class.php");
?>