<?php
    include_once(DIR_FS_CLASSES."users.class.php");
    include_once(DIR_FS_CLASSES."admin.class.php");
    include_once(DIR_FS_CLASSES."manage_broker.class.php");
    include_once(DIR_FS_CLASSES."manage_account.class.php");
    include_once(DIR_FS_CLASSES."manage_product.class.php");
    include_once(DIR_FS_CLASSES."manage_payroll.class.php");
    include_once(DIR_FS_CLASSES."client_suitebility.class.php");
?>